USE [master]
GO

/****** Object:  Database [HotelManagement]    Script Date: 3/2/2022 4:19:38 PM ******/
CREATE DATABASE [HotelManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HotelManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HotelManagement.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HotelManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HotelManagement_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HotelManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HotelManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HotelManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HotelManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HotelManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HotelManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [HotelManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HotelManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HotelManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HotelManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HotelManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HotelManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HotelManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HotelManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HotelManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HotelManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HotelManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HotelManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HotelManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HotelManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HotelManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HotelManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HotelManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HotelManagement] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HotelManagement] SET  MULTI_USER 
GO

ALTER DATABASE [HotelManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HotelManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HotelManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HotelManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HotelManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HotelManagement] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HotelManagement] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HotelManagement] SET  READ_WRITE 
GO


